name: Docker Image Build and Release

on:
  push:
    paths:
      - github-token-manager/**
      - runpod/**

jobs:
  bake:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context:
          - github-token-manager
          - runpod_260
          - runpod_280
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set build variables
        id: build_vars
        run: |
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "short_commit=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo -n "check_dir=" >> $GITHUB_OUTPUT
          docker buildx bake -f docker-bake.hcl --print ${{ matrix.context }} | jq -r '.target."${{ matrix.context }}".context' >> $GITHUB_OUTPUT

      - name: Check changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            changed:
            - '${{ steps.build_vars.outputs.check_dir }}/**'

      - name: Build and push
        uses: docker/bake-action@v6
        if: steps.changes.outputs.changed == 'true'
        env:
          DOCKER_BUILD_RECORD_RETENTION_DAYS: 3
        with:
          push: true
          targets: ${{ matrix.context }}
          set: |
            *.args.GITHUB_SHA=${{ github.sha }}
            *.args.GITHUB_SHA_SHORT=${{ steps.build_vars.outputs.short_commit }}
            *.args.BUILD_DATE=${{ steps.build_vars.outputs.build_date }}
