name: Manual Build and Release
run-name: Build image for ${{ inputs.repository }}

on:
  workflow_dispatch:
    inputs:
      repository:
        description: Repository name with owner
        type: string
        required: true
      ref:
        description: The branch, tag or SHA to checkout
        type: string
        required: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub login
        id: auth
        uses: TimoWilhelm/action-github-app-auth@v1.0.0
        with:
          app-id: ${{ vars.GH_APP_ID }}
          installation-id: ${{ vars.GH_APP_INSTALLATION_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          set-git-credentials: true

      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          token: ${{ steps.auth.outputs.access-token }}
          submodules: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set build variables
        id: build_vars
        run: |
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "short_commit=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "image_tag=${{ vars.DOCKERHUB_USERNAME }}/$(basename ${{ inputs.repository }})" >> $GITHUB_OUTPUT

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          build-args: |
            GITHUB_SHA=${{ github.sha }}
            GITHUB_SHA_SHORT=${{ steps.build_vars.outputs.short_commit }}
            BUILD_DATE=${{ steps.build_vars.outputs.build_date }}
          context: .
          push: true
          tags: ${{ steps.build_vars.outputs.image_tag }}

      - name: Scan for vulnerabilities
        id: scan
        uses: crazy-max/ghaction-container-scan@v3
        continue-on-error: true
        env:
          TRIVY_SKIP_DIRS: "**/.venv"
        with:
          image: ${{ steps.build_vars.outputs.image_tag }}
          dockerfile: ./Dockerfile
          severity_threshold: HIGH
          annotations: true
